### ISSUE TITLE
Adding more memory?

### ISSUE THREAD

**Issue by kdvolder** [cloudfoundry-incubator/cfdev#103]
Is it possible to add more memory/disk to cf dev (like it was possible in the old pcfdev were you could pass some options to the 'start' command to create larger VM to run it on)?

I tried `cf dev --help`, `cf dev start --help` but no information about this. 

I also read the readme here: https://github.com/cloudfoundry-incubator/cfdev/blob/master/README.md

**Comment by aemengo** [comment]
The help commands can be accessed like so:

```
cf dev help start
```

You cannot configure the disk size but you can configure the memory with the `-m` flag, much like before.

```
cf dev start -m 20000
```
