### ISSUE TITLE
CF Dev info

### ISSUE THREAD

**Issue by pankrator** [cloudfoundry-incubator/cfdev#105]
I am registering many service brokers at the same time and doing enable service access for something like 200 plans and 100 organizations. It is about 20000 enable service access requests and Cloud Controller is not able to handle all of them.
CF Dev is started with 32G of memory and 8 cores.

So my questions are:
* What is the number of instances of Cloud Controller?
* Can they be increased?

**Comment by aemengo** [comment]
> What is the number of instances of Cloud Controller?

1

> Can they be increased?

Yes, if you're familiar with the BOSH ecosystem. You'll need to get the manifest and scale the `instance_count:`.

**Comment by aemengo** [comment]
> What is the number of instances of Cloud Controller?

1

> Can they be increased?

Yes, if you're familiar with the BOSH ecosystem. You'll need to get the manifest and scale the appropriate `instance_count:`. For example:

```bash
$ eval "$(cf dev bosh env)"
$ bosh -d cf manifest > cf.yml
... # Edit the manifest with the appropriate count
$ bosh -d cf deploy cf.yml
```

For more information on BOSH, visit here: https://bosh.io/docs/
