### ISSUE TITLE
RTNETLINK answers: Operation not permitted

### ISSUE THREAD

**Issue by Xhings** [cloudfoundry-incubator/cfdev#106]
Hello,

Trying to run ```tc``` command in a local instance and getting below exception:

```RTNETLINK answers: Operation not permitted```

Possibly due to privilege issue hence trying sudo. Are there default credentials?

Regards,
Xhings

**Comment by aemengo** [comment]
What do you mean by in a local instance? What commands are you performing to access the instance?

**Comment by Xhings** [comment]
```cf ssh``` Its a local cfdev instance.

**Comment by aemengo** [comment]
@Xhings If you are performing `cf ssh`, that means that you are ssh'ing under the application developer persona. On any incarnation of Cloud Foundry, `sudo` access is unavailable to the application developer, not just CF Dev. This is expected behavior.
