### ISSUE TITLE
Add warning when "SELinux" is set to "Enforcing"

### ISSUE THREAD

**Issue by joaompinto** [cloudfoundry-incubator/cfdev#108]
→ cat /etc/redhat-release 
Fedora release 30 (Thirty)

→ cf  plugins
Listing installed plugins...

plugin   version   command name   command help
cfdev    0.0.16    dev            Start and stop a single vm CF deployment running on your workstation

-> cf dev start
Downloading Resources...
Progress: |====================>| 100.0%
Setting State...
Creating the VM...
Starting the VM...
Fetching VM Address...
FAILED
cf dev start: exit status 1

**Comment by joaompinto** [comment]
I have found that the problem was related to SELinux preventing the "org.cloudfoundry.cfdev.linuxkit.service" to work was expected.  
It sould be easy to check and warn about potential problems if selinux is enabled.

**Comment by aemengo** [comment]
Thank you for reporting the resolution to the issue. We will consider the product enhancement that you have suggested.
