### ISSUE TITLE
Fail occured after executing "cf install-plugin cfdev" in ubutnu 18.04.2

### ISSUE THREAD

**Issue by Kaysun93** [cloudfoundry-incubator/cfdev#112]
Hi!
&emsp;I do not know whether it is right to ask here, if not, please criticize me lightly...
&emsp;I have tried many times with PCF Dev in my Win10 PC. I downloaded "pcfdev-v0.29.0+PCF1.11.0-windows.exe" and "pcfdev-v0.548.0.ova" to set my local environment up, but it stuck on "Waiting for services to start...", I have no way to solve it with no success...
&emsp;So I turned to cfdev, but it seems bad start to me also. 
&emsp;This is the capture after executing "cf install-plugin cfdev"
    
![图片](https://user-images.githubusercontent.com/41850822/63747810-91706a00-c8da-11e9-8534-2e090403bf54.png)
&emsp;I could install it successfully on my Win10 PC, but it failed in my virtualbox with Ubuntu 18.04.2. Hope anyone could help me to start my cfdev once! :)

**Comment by aemengo** [comment]
CF Dev spins up a VM on your local machine. This is a fairly intensive process and attempting perform the start process inside another VM is not recommended nor supported.
