### ISSUE TITLE
Fedora Silverblue toolbox: qemu-system-x86_64: could not configure /dev/net/tun (cfdevtap0): Operation not permitted

### ISSUE THREAD

**Issue by zamber** [cloudfoundry-incubator/cfdev#117]
OS: Fedora Silverblue 30
Environment: toolbox (https://github.com/debarshiray/toolbox)

In short Silverblue is an immutable Fedora and toolbox is a a qemu/libvirt container with regular fedora for development work. The toolbox can be disposed of if we don't need it anymore, so that the core OS is not polluted by randomly installed packages. The toolbox has DBus and other host OS directories mounted, so that it's possible to run other qemu/libvirt containers from within it. Overall the stability of the OS is awesome and you can always rollback to a working image if something goes wrong.

As of now Silverblue is mostly a desktop OS, but the ultimate goal (as I see it) is to have an ultra-stable host OS for cloud containerization. Toolbox is essentially a bash script automating the creation of a, no pun intended, toolbox with podman (https://podman.io/, ie. `alias docker="podman"`).

I had to install these packages:
- `iproute` for the `ip` command
- `initscripts` for the `service` command

I can't get it to start:

```❯ sudo cf7 dev start
Downloading Resources...
Progress: |====================>| 100.0%
Setting State...
ioctl(TUNSETIFF): Operation not permitted
Error: argument "virbr0" is wrong: Device does not exist

Cannot find device "virbr0"
Cannot find device "cfdevtap0"
Creating the VM...
Starting the VM...
Fetching VM Address...
FAILED
cf dev start: exit status 1
```

```
⬢[root@toolbox pz]# cat /root/.cfdev/log/linuxkit.log 
Using existing disk [/root/.cfdev/state/linuxkit/disk.qcow2] format qcow2
qemu-system-x86_64: could not configure /dev/net/tun (cfdevtap0): Operation not permitted
time="2019-09-26T20:14:24+02:00" level=fatal msg="exit status 1" 
```

I found this, so it's possibly fixable, but I don't know how to do it (yet) https://unix.stackexchange.com/questions/243382/making-dev-net-tun-available-to-qemu

Am I going in the right direction?

**Comment by aemengo** [comment]
As noted in the following issue, `Ubuntu` linux is the only supported distro for this product:

https://github.com/cloudfoundry-incubator/cfdev/issues/129
