### ISSUE TITLE
FAILED to start cf dev

### ISSUE THREAD

**Issue by AdamJel** [cloudfoundry-incubator/cfdev#124]
Hello, I have a trouble with starting the dev using `cf dev start`.

What I did is a complete fresh install of cf onto Windows 10. I installed the dev plugin and started using command `cf dev start`. That worked and process successfully started. But I realized that I did not set the environment variable `CFDEV_HOME` and thus used wrong folder. Then I Ctrl-C the process and (unwisely) deleted `.cfdev` folder.

Since then, I get error when I try to start the cf dev again.

I already reinstalled Hyper-V and cf completely, but with no luck. The error I get is:
```
FAILED
cf dev start: stopping cfdev: cf dev stop: failed to stop the VM: failed to stop vpnkit: Failed to execute C:\Users\jelinek\.cfdev\winservice\org.cloudfoundry.cfdev.vpnkit\org.cloudfoundry.cfdev.vpnkit.exe, [C:\Users\jelinek\.cfdev\winservice\org.cloudfoundry.cfdev.vpnkit\org.cloudfoundry.cfdev.vpnkit.exe uninstall]: exec: "C:\\Users\\jelinek\\.cfdev\\winservice\\org.cloudfoundry.cfdev.vpnkit\\org.cloudfoundry.cfdev.vpnkit.exe": file does not exist:
```

Any advice, please?

**Comment by aemengo** [comment]
I'd recommend that you do a full reboot. Then delete the `.cfdev` folder. And then you should be able to safely perform a `cf dev start` (with / without the `CFDEV_HOME` variable set).

**Comment by AdamJel** [comment]
> 
> 
> I'd recommend that you do a full reboot. Then delete the `.cfdev` folder. And then you should be able to safely perform a `cf dev start` (with / without the `CFDEV_HOME` variable set).

This doesnt work. As I stated - after not only full reboot, but after reinstalling all components (and reboot and .cfdev folder deletion), `cf dev start` fails into the error above.

**Comment by aemengo** [comment]
I see.

Are you familiar with the “Hyper-V Manager“ application? Could you open it and see if there is a VM titled “cfdev” there? If so, please delete it and try again.

**Comment by AdamJel** [comment]
> 
> 
> I see.
> 
> Are you familiar with the “Hyper-V Manager“ application? Could you open it and see if there is a VM titled “cfdev” there? If so, please delete it and try again.

I just checked, there is no VM at all. So I deleted the server for current user. But `cf dev start` still fails the same way.

**Comment by aemengo** [comment]
Could you perform `Get-Service | findstr vpnkit` on the Powershell command line? Do you see anything? If so, could you please remove the service and try again?

**Comment by AdamJel** [comment]
> 
> 
> Could you perform `Get-Service | findstr vpnkit` on the Powershell command line? Do you see anything? If so, could you please remove the service and try again?

There was stopped service:
```
Get-Service | findstr vpnkit
Stopped  org.cloudfoundr... org.cloudfoundry.cfdev.vpnkit
```
So I removed it:
```
Remove-Service -Name "org.cloudfoundry.cfdev.vpnkit"
Get-Service "*vpnkit*" | Sort-Object status
>
```

It seems to work. I am downloading resources right now. 
Ok - thank you so  much! 👍
