### ISSUE TITLE
Get https://plugins.cloudfoundry.org/list: dial tcp ip: i/o timeout

### ISSUE THREAD

**Issue by ajinkya976** [cloudfoundry-incubator/cfdev#127]
Hi,

Can someone please help in this error.

Get **https://plugins.cloudfoundry.org/list: dial tcp ip: i/o timeout**

i am trying to execute **cf install-plugin -r CF-Community cfdev** in my linux machine.

**Comment by aemengo** [comment]
Please make sure you can access the URL from a web browser. You seem to be have networking difficulties that is out of scope for this repository.

**Comment by ajinkya976** [comment]
i can access url in browser but it open some content

**Comment by aemengo** [comment]
You seem to be having trouble installing _any cf plugin_ at all, not just CF Dev. Perhaps you'd have better luck at this repository:
https://github.com/cloudfoundry/cli
