### ISSUE TITLE
State in the doc that the only supported Linux distribution is Ubuntu

### ISSUE THREAD

**Issue by marcello-dev** [cloudfoundry-incubator/cfdev#129]
I don't see anywhere that the only supported distribution is Ubuntu, only [here](https://github.com/cloudfoundry-incubator/cfdev/issues/119#issuecomment-599245144). The installation fails on RHEL7 and CentOS 7 as explained on the issue #119.

**Comment by aemengo** [comment]
This is a good call. Sorry for any confusion.
