### ISSUE TITLE
Binding error: "Service broker error: Could not find an available leader"

### ISSUE THREAD

**Issue by marcello-dev** [cloudfoundry-incubator/cfdev#130]
I have deployed a Spring Boot app and mysql on my PCFDEV instance running on Ubuntu. 
This is the error I get when I try to bind mysql to the app:
`Service broker error: Could not find an available leader from [https://10.144.0.8:8443]`

The full list of commands from the start is:
```
cf dev start -f pcfdev-v1.2.0-linux.tgz
cf login -a https://api.dev.cfdev.sh --skip-ssl-validation
cf push
cf dev deploy-service mysql
cf create-service p.mysql db-small  mysql-instance
cf bind-service demo-customer mysql-instance
```

The issue is on the last command which outputs:

> Your CF API version (2.125.0) is no longer supported. Upgrade to a newer version of the API (minimum version 2.128.0). Please refer to https://github.com/cloudfoundry/cli/wiki/Versioning-Policy#cf-cli-minimum-supported-version
Binding service mysql-instance to app demo-customer in org cfdev-org / space cfdev-space as admin...
Service broker error: Could not find an available leader from [https://10.144.0.8:8443]
FAILED

**Comment by aemengo** [comment]
Please perform the following instead

```
cf create-service p-mysql 10mb mysql-instance 
```

CF Dev ships with `p-mysql` not `p.mysql`. Thus the workflow that you've posted above is not supported.

**Comment by hfcotino** [comment]
Hi, I get the same error when binding or creating a service key. I've tried on Windows as well as on Linux, but get the same error. Is there a solution for this?

**Comment by marcello-dev** [comment]
> Hi, I get the same error when binding or creating a service key. I've tried on Windows as well as on Linux, but get the same error. Is there a solution for this?

Have you tried the [solution](https://github.com/cloudfoundry-incubator/cfdev/issues/130#issuecomment-628662473) suggested by @aemengo ? I haven't tried it yet.

**Comment by hfcotino** [comment]
> > Hi, I get the same error when binding or creating a service key. I've tried on Windows as well as on Linux, but get the same error. Is there a solution for this?
> 
> Have you tried the [solution](https://github.com/cloudfoundry-incubator/cfdev/issues/130#issuecomment-628662473) suggested by @aemengo ? I haven't tried it yet.

With PCFDev I only got p.mysql. I did however also tried CFDev which has de p-mysql broker. This works fine, the only problem is it only has 10mb or 20mb plans, which is too small.

**Comment by aemengo** [comment]
@hfcotino @marcello-dev I think there's some confusion. The plans `10mb` and `20mb` are effectively just labels to match what a real `cf-mysql` deployment would give you. However, unlike a real deployment, services are allocated _all free space_ in the VM. And this goes for most of the services.

CF Dev aims to provide you with the same interaction experience that you would get with a full deployment, not the same performance or resource expectations.
