### ISSUE TITLE
Cache the state of cf dev

### ISSUE THREAD

**Issue by vinayu** [cloudfoundry-incubator/cfdev#37]
Hello,

Could you add a feature to cache the state of cf dev to survive a restart quickly vs having going through a redeployment of bosh,cf and services on every start? 30 minutes to start cf dev is just too much to wait.

**Comment by ssisil** [comment]
hi @vinayu - this is something we have prioritized in our backlog. We hope to have improvements related to start up out in the coming months

**Comment by geofffranks** [comment]
+1

**Comment by aemengo** [comment]
some improvements in this area available in **v0.0.13**. Estimated start up time is now ~10min.
