### ISSUE TITLE
What is root ca/ssl cert for uaa.v3.pcfdev.io?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/cfdev#39]
I have a demo app [1] which accepts `$UAA_CA_CERT_FILE` as a reference to the UAA's custom root CA.

I'm having troubles figuring out where in the `bosh -d cf manifest` the root CA for the https://uaa.v3.pcfdev.io and https://login.v3.pcfdev.io is.

A good candidate looked like:

```
bosh int <(bosh -d cf manifest) --path /instance_groups/name=api/jobs/name=routing-api/properties/uaa/ca_cert
```

But its not working for the demo app:

```
bosh int <(bosh -d cf manifest) --path /instance_groups/name=api/jobs/name=routing-api/properties/uaa/ca_cert > tmp/cfdev-uaa.cert
export UAA_URL=https://uaa.v3.pcfdev.io
export UAA_CA_CERT=$(bosh int <(bosh -d cf manifest) --path /instance_groups/name=api/jobs/name=routing-api/properties/uaa/ca_cert)

docker run -ti -p 9292:9292 -e UAA_URL=$UAA_URL -e UAA_CA_CERT=$UAA_CA_CERT \
    starkandwayne/uaa-example-omniauth-login-only
```

(see [1] for setup of client + sample user)

But when the authorized grant returns back from my UAA, my client errors with:

```
D, [2018-08-02T08:52:03.100070 #13013] DEBUG -- omniauth: <---- no response due to exception: #<CF::UAA::SSLException: Invalid SSL Cert for https://login.v3.pcfdev.io/oauth/token. Use '--skip-ssl-validation' to continue with an insecure target>
```

What is the correct SSL cert/root CA for cfdev endpoints?

[1] https://github.com/starkandwayne/ultimate-guide-to-uaa-examples/tree/master/ruby/omniauth-login-only

**Comment by drnic** [comment]
I've also tried:

```
source <(cf dev bosh env)
export UAA_URL=https://login.v3.pcfdev.io
export UAA_CA_CERT_FILE=${BOSH_CA_CERT}
export UAA_CA_CERT=$(cat $UAA_CA_CERT_FILE)
```

**Comment by drnic** [comment]
Is the issue related to the UAA's sslCertificate only having `uaa.service.cf.internal` as its alternate name, and not `uaa.v3.pcfdev.io`?

```
$ openssl x509 -text -in <(bosh int <(bosh -d cf manifest) --path /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/sslCertificate)
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            6a:fe:4b:a4:e0:0b:a3:8a:a7:ef:08:50:c9:28:22:af
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=USA, O=Cloud Foundry, CN=uaaCA
        Validity
            Not Before: Aug  1 22:33:51 2018 GMT
            Not After : Aug  1 22:33:51 2019 GMT
        Subject: C=USA, O=Cloud Foundry, CN=uaa.service.cf.internal
...
```

**Comment by drnic** [comment]
This one looked good but failed:

```
$ bosh int <(bosh -d cf manifest) --path /instance_groups/name=router/jobs/name=gorouter/properties/router/tls_pem/0/cert_chain
...
            X509v3 Subject Alternative Name:
                DNS:v3.pcfdev.io, DNS:*.v3.pcfdev.io
```

```
export UAA_URL=https://uaa.v3.pcfdev.io
export UAA_CA_CERT=$(bosh int <(bosh -d cf manifest) --path /instance_groups/name=router/jobs/name=gorouter/properties/router/tls_pem/0/cert_chain)
export UAA_CA_CERT_FILE=$(mktemp)
echo "$UAA_CA_CERT" > $UAA_CA_CERT_FILE

curl https://uaa.v3.pcfdev.io/login -H 'Accept: application/json' --cacert ${UAA_CA_CERT_FILE}
```

But perhaps the cert above isn't a ca.

**Comment by drnic** [comment]
I also tried `/instance_groups/name=router/jobs/name=gorouter/properties/router/tls_pem/0/cert_chain`

**Comment by ekcasey** [comment]
Hi @drnic CF inside of `cfdev` is deployed with `cf-deployment`. The uaa ssl cert is defined as a variable in the manifest and generated on deploy https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L1936-L1942. 

```
- name: uaa_ssl
  type: certificate
  options:
    ca: uaa_ca
    common_name: uaa.service.cf.internal
    alternative_names:
    - uaa.service.cf.internal
```
If you want to use `bosh int` to retrieve it from the manifest it can be found at
```
bosh int <(bosh -d cf manifest) --path /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/sslCertificate
```
The `uaa_ca` that signs the `uaa_ssl` cert is also a generated variable that can be extracted from the manifest. From here for example https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L786

You are right that the cert only has `uaa.service.cf.internal` as an alternate name, not `uaa.v3.pcfdev.io`. 

The cert you really want is the `router` cert if you are accessing `uaa.v3.pcfdev.io`. The `router_ssl` cert and the `router_ca` are also manifest variables. You can grab the router cert from interpolated cf manifest but not the router ca. I'm not sure why you last attempt didn't work. The following worked for me...
```
bosh int <(bosh -d cf manifest) --path /instance_groups/name=router/jobs/name=gorouter/properties/router/tls_pem/0/cert_chain > router_cert
curl -I https://uaa.v3.pcfdev.io/login 'Accept: application/json' --cacert router_cert
HTTP/1.1 200 OK
...
```
Is it possible that the way you are grabbing the ca cert into the `UAA_CA_CERT` variable is resulting in a poorly formatted cert? 

Let me know if you are still having issues. I just ran this test against a recent dev version. If are still having trouble I can test out the version of `cfdev` you are using.

**Comment by drnic** [comment]
The plot thickens. The above command fails for me:

```
$ bosh int <(bosh -d cf manifest) --path /instance_groups/name=router/jobs/name=gorouter/properties/router/tls_pem/0/cert_chain > router_cert
$ curl -I https://uaa.v3.pcfdev.io/login 'Accept: application/json' --cacert router_cert

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
...
```

Contents of `router_cert` file look fine via `openssl x509 -text -in router_cert`.

Ideas what might be busted with my `curl` or local envirionment?

**Comment by drnic** [comment]
Ok, I upgraded MacOS `curl` with homebrew and its not failing now:

```
$ brew install curl
$ export PATH="/usr/local/opt/curl/bin:$PATH"
$ curl --version
curl 7.61.0 (x86_64-apple-darwin17.6.0) libcurl/7.61.0 SecureTransport zlib/1.2.11
```

**Comment by drnic** [comment]
But no idea why preinstalled curl was failing. Ideas?
