### ISSUE TITLE
Date on bosh instance is wrong so certificates aren't valid yet

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/cfdev#40]
On my laptop in GMT+10:

```
$ date
Wed  1 Aug 2018 13:42:07 AEST
```

So the GMT time would be `03:42:07`.

But inside a cfdev bosh instance I see an older time:

```
# date
Wed Aug  1 00:14:32 UTC 2018
```

Amusing perhaps, but it means that the certificates I generate on my laptop are not yet valid for another 3.5 hours.

Any ideas about this?

Note: my cfdev is not recently deployed; so my guess is an ntp configuration issue. Are we configuring ntp?

**Comment by ekcasey** [comment]
@drnic You are right, it looks like we are missing `ntpd` from our image. Sleeping your laptop would likely result in time drift between the host and guest. I'll add this to the backlog.

Your feedback is very much appreciated :)

**Comment by drnic** [comment]
Ahh yeah lol. I always assume time continues onwards; but not if you freeze the VM :)

**Comment by aemengo** [comment]
The most recent release [v0.0.10](https://github.com/cloudfoundry-incubator/cfdev/releases/tag/0.0.10) should have this resolved.
