### ISSUE TITLE
Trigger request for root password sooner

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/cfdev#41]
As a regular user of `cf dev stop` and later `cf dev start`, and knowing that it takes 30 mins to bootstrap, I start the command and walk away. Only to come back in 10-30 mins to see it waiting for my root password.

Can we please trigger the prompts for user interactions (root password in this case) ASAP before going into other long running behaviour?

Merci
Nic

**Comment by ekcasey** [comment]
@drnic Thanks for the feedback! That is definitely something we can work on improving. I threw a story in the backlog to address this.

**Comment by sdawson-pivotal** [comment]
@drnic would you mind sharing a bit about your use case? We are looking to better understand how people are using CF / PCF Dev, and what they are looking for. Your answers to this 4 question survey would be very helpful to us: https://goo.gl/forms/3OHzU2S5907hiu5r1

**Comment by drnic** [comment]
IMO a program should immediately prompt for all information it might need. When I raised this ticket, the command would start running and not prompt, so you’d walk away and wait 30 mins for it to complete. You’d come back and it would be prompting for sudo access; and wouldn’t have yet started the rest of the 30+ mins of work.

I haven’t used newer cfdev releases for a couple months sorry.
