### ISSUE TITLE
Can't start the pcf dev using iso file

### ISSUE THREAD

**Issue by grindrt** [cloudfoundry-incubator/cfdev#42]
Hello everyone, 

I'm trying to start the PCF Dev using the .iso file from this page:  https://network.pivotal.io/products/pcfdev#/releases/152982

But during execution of the cf dev start command I've faced with next exception (I'm running command using an administrator mode): 

PS C:\WINDOWS\system32>  cf dev start -f C:\pcf\pcfdev-pas.v.2.0.18.0-build.0.75.0.iso -m 8096
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
FAILED
cf dev start: adding aliases: exit status 1

**Comment by ssisil** [comment]
hi @grindrt - do you have Hyper-V enabled on your machine ? You can follow this tutorial if you do not - https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

**Comment by grindrt** [comment]
Hi @ssisil , yes, enabling of the Hyper-V helped me. Thanks!

**Comment by sdawson-pivotal** [comment]
@grindrt would you mind sharing a bit about your use case? We are looking to better understand how people are using CF Dev, and what they are looking for. Your answers to this 4 question survey would be very helpful to us: https://goo.gl/forms/3OHzU2S5907hiu5r1
