### ISSUE TITLE
hyper-v detect logic not works in windows server 2016.

### ISSUE THREAD

**Issue by andyliuliming** [cloudfoundry-incubator/cfdev#45]

**Comment by aemengo** [comment]
Thanks very much for your assistance with this. This issue has been addressed in the following commit:
https://github.com/cloudfoundry-incubator/cfdev/commit/71709accd70ba22b794fca15458667ec80fa68bc

Be on the lookout for our next release

**Comment by andyliuliming** [comment]
@aemengo Hi, Anthony, the fix you did is not 100% correct. because the "Hyper-V Module for Windows PowerShell" can live without Hyper-V feature.
so only check the "Hyper-V Module for Windows PowerShell" on windows server 2016 is not enough.
could you please help merge my commit, thanks.

**Comment by aemengo** [comment]
PR: https://github.com/cloudfoundry-incubator/cfdev/pull/46 has been merged
