### ISSUE TITLE
cf dev start: Failed to deploy services: unable to parse bosh config: yaml: line 1: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by rockebee** [cloudfoundry-incubator/cfdev#47]
Hi devs,
After having workarounded the issue with non-english environment on Windows, I now stumbled upon another issue:
```
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
Downloading Resources...
Creating the VM...=============>| 100.0%
Starting VPNKit...
Starting the VM...
Waiting for Garden...
Deploying the BOSH Director...
Deploying CF...
  Uploading ReleasesFAILED
cf dev start: Failed to deploy services: unable to parse bosh config: yaml: line 1: mapping values are not allowed in this context
```

Any hint or idea where to look at?
The `cache\cf-deps.iso` file has been newly downloaded (size is 4.882.026..240 bytes), and from what I see there are no relevant logs on my windows machine that might help ...

As the VM is still up and running: Is there any way to log in to it (e. g. via SSH) and check guest machine logs? (if that could help at all)

**Comment by aemengo** [comment]
We apologize very much, but this is very likely due to an intermittent bug that will be resolved in our upcoming release.

But the good news is that, although provisioning did not complete 'till the very end, your local Cloud Foundry deployment should be up and available for use. Here's the interaction instructions that you would have seen.

```
 	
 	  ██████╗███████╗██████╗ ███████╗██╗   ██╗
 	 ██╔════╝██╔════╝██╔══██╗██╔════╝██║   ██║
 	 ██║     █████╗  ██║  ██║█████╗  ██║   ██║
 	 ██║     ██╔══╝  ██║  ██║██╔══╝  ╚██╗ ██╔╝
 	 ╚██████╗██║     ██████╔╝███████╗ ╚████╔╝
 	  ╚═════╝╚═╝     ╚═════╝ ╚══════╝  ╚═══╝
 	             is now running!
 	
 	To begin using CF Dev, please run:
 	    cf login -a https://api.dev.cfdev.sh --skip-ssl-validation
 	
 	Admin user => Email: admin / Password: admin
 	Regular user => Email: user / Password: pass
```

**Comment by rockebee** [comment]
Hi @aemengo,
I verified that login works with the given credentials, so thanks for the hint. However, after having logged in I don't have any services listed in the marketplace nor is the web ui working (returning 404 on https://apps.dev.cfdev.sh), so the cfdev environment is kinda ... useless for me :/ 
I assume this is related to the bosh deployment error quoted above, but is there any other way to get a marketplace service (in this case the MySQL tile) added to cfdev?

If not: When do you expect a new cfdev release with a fix for the bootstrapping process will be made available? I'd be also happy to test before a release in case you provide me a github link to the plugin to download from ...

Thanks for your support!

**Comment by ssisil** [comment]
@rockebee - Im assuming you are starting this in open source mode - ie. `cf dev start`. If so - you will only have access to MySQL service. Apps Manager, Redis, RabbitMQ are only available when you start in PCF Dev mode - which is `cf dev start -f <path to .iso>`. You should be able to download the .iso file from the PCF Dev page on network.pivotal.io

**Comment by sdawson-pivotal** [comment]
@rockebee would you mind sharing a bit about your use case? We are looking to better understand how people are using CF / PCF Dev, and what they are looking for. Your answers to this 4 question survey would be very helpful to us: https://goo.gl/forms/3OHzU2S5907hiu5r1

**Comment by existme** [comment]
I am encountering the same problem

**Comment by aemengo** [comment]
@existme Please ensure that you're on the latest version of our product

```
$ cf dev version
CLI: v0.0.16
...
```
