### ISSUE TITLE
As CF Dev user, I can specify a service that I want to start with the `-s` flag

### ISSUE THREAD

**Issue by ssisil** [cloudfoundry-incubator/cfdev#49]
**Scenario : Filtering services**

__WHEN__ I pass in a  service with the `-s` flag in `cf dev start`
__THEN__ only the specified services will be started

**Scenario : `all` specified CF Dev**
__WHEN__ I pass in `all` to the `-s` flag in `cf dev start` 
__THEN__ mysql service will be included in the cf dev instance

**Scenario : `none` specified**
__WHEN__ I pass in `none` to the `-s` flag in `cf dev start` 
__THEN__ no services will be started

**Comment by aemengo** [comment]
available in **v0.0.13**
