### ISSUE TITLE
windows cf dev fails on deploying bosh director

### ISSUE THREAD

**Issue by bennedm** [cloudfoundry-incubator/cfdev#51]
When trying to start cf dev on a windows 10 machine, it fails while deploying the bosh director with the following message:

cf dev start: Failed to deploy the BOSH Director: process exited with status 1

I'm not sure where or how to look for more information to diagnose this problem.
output of version command:
D:\cf-dev>cf dev version
CLI: 0.0.10
cf: v4.3.0
cf-mysql: 36.15.0

**Comment by aemengo** [comment]
@bennedm Would you mind telling us how much ram your workstation has? We've routinely seen this sort of behavior with workstations that have limited amounts of memory.

**Comment by bennedm** [comment]
Sorry for the late reply, I have 16 GB of ram in this machine. I can try without other applications opened if that might help

**Comment by dkadam77** [comment]
Is there any solution to this issue??? I am also facing the same issue.

**Comment by aemengo** [comment]
@airduster Our newest release **v.0.0.13** is out, with major performance updates! Please give this a try and let us know if your issue is fixed.

```powershell
$ cf dev stop
$ Remove-Item -Recurse -Force ~/.cfdev
$ cf install-plugin -r CF-Community "cfdev"
$ cf dev start
```

**Comment by sdawson-pivotal** [comment]
@bennedm would you mind sharing a bit about your use case? We are looking to better understand how people are using CF / PCF Dev, and what they are looking for. Your answers to this 4 question survey would be very helpful to us: https://goo.gl/forms/3OHzU2S5907hiu5r1
