### ISSUE TITLE
v0.0.11 is not compatible with pcfdev iso

### ISSUE THREAD

**Issue by exzine** [cloudfoundry-incubator/cfdev#53]
Hi, this update won't work with current pcfdev iso file (v2.0.20.0build0.82.0), please check that.

**Comment by ssisil** [comment]
@exzine - Thanks - we plan on releasing a new version of the pcfdev.iso that works with v 0.0.11 very soon.  In the mean time - we recommend going back to a version v 0.0.10 or using it in CF only mode

**Comment by ssisil** [comment]
Latest release of PCF Dev - https://network.pivotal.io/products/pcfdev#/releases/216556
is compatible with CF Dev plugin v0.0.12 or higher.
