### ISSUE TITLE
bosh ssh

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry-incubator/cfdev#56]
I need to set bosh deployment in order to "bosh ssh"
How do I set it? or can I even "bosh ssh"
Thanks

**Comment by aemengo** [comment]
You perform the command by setting the `-d / --deployment` flag (mileage may vary on Windows). For instance, with CF Dev on a `macOS` system:

```bash
$ eval "$(cf dev bosh env)"
$ bosh -d cf ssh api
```

In the future, please understand that this question is better suited for the [BOSH CLI repository](https://github.com/cloudfoundry/bosh-cli/issues) or even by consulting their [documentation](https://bosh.io/docs/cli-v2/#ssh-mgmt). This repository and its issues are only intended for discussing the _packaging and provision_ of Cloud Foundry for a Desktop environment.
