### ISSUE TITLE
resources available in diego cell

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry-incubator/cfdev#57]
"http://localhost:1801/state" returns nothing in diego cell, instead of available resources

**Comment by aemengo** [comment]
@betht1220 It's quite vexing but cloudfoundry has locked itself down considerably from a security standpoint. The endpoint you've mentioned should be able to reached via mutual TLS. Please give the following a try in the diego cell and see if it yields better results:

```
curl \
  --cert /var/vcap/jobs/rep/config/certs/tls.crt \
  --key /var/vcap/jobs/rep/config/certs/tls.key \
  --cacert /var/vcap/jobs/rep/config/certs/tls.crt \
  https://localhost:1801/state
```
