### ISSUE TITLE
documentation: RAM required 

### ISSUE THREAD

**Issue by joaompinto** [cloudfoundry-incubator/cfdev#63]
The documentation with system requirements should note that on Windows 10 more than 8GB of RAM are required.

**Comment by aemengo** [comment]
Addressed with: https://github.com/cloudfoundry-incubator/cfdev#recommended-system-requirements
Thanks!

**Comment by sdawson-pivotal** [comment]
@joaompinto would you mind sharing a bit about your use case? We are looking to better understand how people are using CF Dev, and what they are looking for. Your answers to this 4 question survey would be very helpful to us: https://goo.gl/forms/3OHzU2S5907hiu5r1

**Comment by joaompinto** [comment]
@sdawson-pivotal done. Thanks for the attention.
