### ISSUE TITLE
Is it possible to use 192.168 IP address?

### ISSUE THREAD

**Issue by emailtowalter** [cloudfoundry-incubator/cfdev#65]
Hi... CF Dev seems to use 10.144.0.34 on my computer for app instance. Here is the problem:  I can curl the app, but my browser cannot connect to this address. It gives me network error. 

After a bit network tracing, I found the root cause: The DNS lookup works fine. But In my company's network, we use PAC file for proxy setting. In the file, 10.144.* is not included as bypass. Hence browser always forwards the dev.cfdev.sh to company proxy server which of course fails. 

I guess I can mess up around the PAC file, but I prefer not. Ideally if I can change the IP to 192.168.* range , it will work as most of the company's proxy setting bypass this range. ( i guess 10.* range is too wide, so it goes with specific sub range).  This also explains why I did not see this issue when using PCFdev since they use 192.168 range.

Is it possible? There might be a problem for dev.cfdev.io DNS setting.

**Comment by sdawson-pivotal** [comment]
Hey @emailtowalter thanks for reaching out. Let me look into this further. I will get back to you with a definitive answer as to whether we have a solution for you at this time.

**Comment by emailtowalter** [comment]
thanks for getting back to me. Too bad. I am sure someone in the future will have the same problem.

**Comment by sdawson-pivotal** [comment]
@emailtowalter would you mind sharing a bit about your use case? We are looking to better understand how people are using CF Dev, and what they are looking for. Your answers to this 4 question survey would be very helpful to us: https://goo.gl/forms/3OHzU2S5907hiu5r1
