### ISSUE TITLE
cf dev start: Failed to deploy the Cloud Foundry: process exited with status 1

### ISSUE THREAD

**Issue by airduster** [cloudfoundry-incubator/cfdev#66]
downloaded latest version of cf cli (cf-cli-installer_6.41.0_winx64.zip) 
and cfdev (cfdev 0.0.12) for Windows 10 running 16gb ram machine. 

After following setup instructions
Attempted to run "cf dev start" and got the following output log/error. 

The error message 

```
Progress: 7 of 14 (53m44s) FAILED
       cf dev start: Failed to deploy the Cloud Foundry: process exited with status 1
```

although it indicates an error occurred doesn't indicate What/Why it occurred. 
What is being attempted at "Progress: 7 of 14"?
Is there a verbose flag we can turn on to see more details? 
RAM usage at time of error was 10GB of 16GB. 

This error quite troublesome to repeat/debug because as you can see from output log. It takes 50m-1hr
to get to the point of the error. 

```
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
Downloading Resources...
Creating the VM...=============>| 100.0%
Starting VPNKit...
Starting the VM...
Waiting for Garden...
Deploying the BOSH Director...
Deploying CF...
          Progress: 7 of 14 (53m44s) FAILED
cf dev start: Failed to deploy the Cloud Foundry: process exited with status 1
```

**Edit:**   Would like to add attempted this 4 more times and got slightly different results but the failures are consistently repeatable. 

Failures occurred at: 

`Progress: 6 of 14 (49m25s)FAILED`
and 
`Progress: 8 of 14 (53m43s)FAILED`
and
`Progress: 7 of 14 (53m15s)FAILED`
and
`Progress: 8 of 14 (54m28s)FAILED`

So from this maybe we can deduce it is not specific to the enumerated logic being performed but the pattern appears to be always at around 53 min mark we see a failure and the start process exits. 

Here is a snapshot of the "vmmem" a couple of minutes before the failure. After the failure the process continues to run, only noticable difference is the disk utilization drops from 99%-> 20-30%. 

![image](https://user-images.githubusercontent.com/2158763/50382482-f0078900-0665-11e9-931e-4d913854f871.png)

**Comment by stevewallone** [comment]
I'm having a similar issue on a Mac. 
```
$ cf dev start
Downloading Network Helper...
Installing cfdevd network helper...00.0%
Installing networking components (requires root privileges)
Password:
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
Downloading Resources...
WARNING: CF Dev requires 8192 MB of RAM to run. This machine may not have enough free RAM.
Creating the VM...
Starting VPNKit...
Starting the VM...
Waiting for Garden...
Deploying the BOSH Director...
Deploying CF...
  Uploading Releases  Uploaded Releases : 0 (1s)  Uploaded Releases: 0 (2s)  Uploaded Releases: 0 (3s)  Uploaded Releases: 0 (4s)  Uploaded Releases: 0 (5s)  Uploaded Releases: 0 (6s)  Uploaded Releases: 0 (7s)  Uploaded Releases: 0 (8s)  Uploaded Releases: 0 (9s)
.
.
.

Uploaded Releases: 35 (13m40s)  Progress: 0 of 8 (13m52s)  Progress: 0 of 14 (13m55s)  Progress: 0 of 14 (13m57s)  Progress: 0 of 14 (13m59s)  Progress: 0 of 14 (14m1s)  Progress: 0 of 14 (14m4s)  Progress: 0 of 14 (14m6s)  Progress: 0 of 14 (14m8s)  Progress: 0 of 14 (14m10s)  Progress: 0 of 14 (14m13s)  Progress: 0 of 14 (14m15s)  Progress: 0 of 14 (14m18s)  Progress: 0 of 14 (14m19s)  Progress: 0 of 14 (14m21s)  Progress: 0 of 14 (14m23s)  Progress: 0 of 14 (14m25s)  Progress: 2 of 14 (14m27s)  Progress: 2 of 14 (14m29s)  Progress: 2 of 14 (14m31s)  Progress: 2 of 14 (14m34s)  Progress: 2 of 14 (14m36s)  Progress: 2 of 14 (14m37s)  Progress: 2 of 14 (14m40s)  Progress: 2 of 14 (14m42s)  Progress: 2 of 14 (14m44s)  Progress: 2 of 14 (14m47s)  Progress: 2 of 14 (14m49s  Progress: 2 of 14 (14m51s)  Progress: 2 of 14 (14m53s)  Progress: 2 of 14 (14m55s)  Progress: 2 of 14 (14m57s)  Progress: 2 of 14 (15m0s)  Progress: 2 of 14 (15m2s)  Progress: 2 of 14 (15m5s)  Progress: 2 of 14 (15m16s)  Progress: 2 of 14 (15m18s)  Progress: 2 of 14 (15m21s)  Progress: 2 of 14 (15m23s)  Progress: 2 of 14 (15m25s)  Progress: 2 of 14 (15m30s)  Progress: 2 of 14 (15m32s)  Progress: 2 of 14 (15m33s)  Progress: 2 of 14 (15m43s)  Progress: 2 of 14 (15m45s)FAILED
cf dev start: Failed to deploy the Cloud Foundry: process exited with status 1

$ cf dev start
CF Dev is already running...
```

**Comment by stevewallone** [comment]
@airduster I figured out my issue. My computer would sleep during the installation. And then fail after it woke up. On the Mac, sleep can be turned off in the `Energy Saver` system preference. Once I turned it off, the installation succeeded.

**Comment by airduster** [comment]
@stevewallone my pc set to never sleep

**Comment by airduster** [comment]
@stevewallone thanks for the hint. Nice windows 10 "gotcha". Even though it is set to "Never Sleep" you have to still explicitly define a value for the hard drive sleep in advanced settings. Got it working now. 

![image](https://user-images.githubusercontent.com/2158763/50387018-d3e10780-06b8-11e9-996f-c50d0cbaf467.png)

**Comment by stevewallone** [comment]
@airduster Glad you were able to figure it out! I'm going to submit a pull request and add this to the README.md. If we both experienced it on different platforms, I'm sure others will too.

**Comment by aemengo** [comment]
@airduster we've gotten reports of CF Dev consuming a lot of resources. Your issue should be addressed with our next release, coming soon.  🙂

**Comment by aemengo** [comment]
@airduster Our newest release **v.0.0.13** is out, with major performance updates! Please give this a try and let us know if your issue is fixed.

```powershell
$ cf dev stop
$ Remove-Item -Recurse -Force ~/.cfdev
$ cf install-plugin -r CF-Community "cfdev"
$ cf dev start
```

**Comment by stevewallone** [comment]
My initial attempt failed. Here's the output. I'll try again. Is there anyway to get more information on what is going on?

```Steves-MacBook-Pro:~ steve$ rm -rf ~/.cfdev
Steves-MacBook-Pro:~ steve$ cf install-plugin -r CF-Community "cfdev"
Searching CF-Community for plugin cfdev...
Plugin cfdev 0.0.13 found in: CF-Community
Plugin cfdev 0.0.12 is already installed.
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to uninstall the existing plugin and install cfdev 0.0.13? [yN]: y
Starting download of plugin binary from repository CF-Community...
 18.38 MiB / 18.38 MiB [=========================================================================================================================] 100.00% 2s
Plugin cfdev 0.0.12 is already installed. Uninstalling existing plugin...
OK
Plugin cfdev successfully uninstalled.
Installing plugin cfdev...
OK
Plugin cfdev 0.0.13 successfully installed.
Steves-MacBook-Pro:~ steve$ cf dev start
Downloading Network Helper...
Progress: |====================>| 100.0%
Installing cfdevd network helper...
Installing networking components (requires root privileges)
Password:
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
Downloading Resources...
Progress: |====================>| 100.0%
Setting State...

CF Dev collects anonymous usage data to help us improve your user experience. We intend to share these anonymous usage analytics with user community by publishing quarterly reports at :
		
https://github.com/pivotal-cf/cfdev/wiki/Telemetry
		
Are you ok with CF Dev periodically capturing anonymized telemetry [y/N]?> y
WARNING: CF Dev requires 8192 MB of RAM to run. This machine may not have enough free RAM.
Creating the VM...
Starting VPNKit...
Starting the VM...
Waiting for the VM...
Deploying the BOSH Director...
Deploying CF...
  Progress: 0 of 0 (10m11s)FAILED
cf dev start: Failed to deploy the Cloud Foundry: Failed to deploy cf: exit status 1```

**Comment by stevewallone** [comment]
I tried again with the same results as above.

**Comment by aemengo** [comment]
@stevewallone Could you please run the following command and report the output?

```
$ cat ~/.cfdev/log/deploy-cf.log

**Comment by stevewallone** [comment]
Here's a zip of the log directory.

[log.zip](https://github.com/cloudfoundry-incubator/cfdev/files/2731280/log.zip)

**Comment by aemengo** [comment]
@stevewallone the `10.144.0.34` address seems to be occupied on your machine. I wonder if you already had an instance of CF Dev running. Please run `cf dev stop` before trying again. And, if that does not work, perhaps consider a machine reboot.

**Comment by airduster** [comment]
@aemengo It is on mine even with the vmmem.exe process killed, I attempted a reboot but `10.144.0.34` IP is still active. Looks like one it fails midway during `cf dev start` it leaves the machine in a bad state and upon bootup retains the special network setting CF is setting up.

**Comment by aemengo** [comment]
@airduster It's not the most intuitive, but running `cf dev stop` when CF Dev fails is the way to "clean-up", *before* running again.

**Comment by airduster** [comment]
@aemengo cf dev start won't execute if I attempt to run it after it fails halfway with an instance already running error. So you have to cf dev stop.

**Comment by codeaches** [comment]
@aemengo I am facing similar issue with "cf dev start -f pcfdev-pas.v.2.0.22.0-build.0.0.71-windows.tgz -s scs". 
I followed https://network.pivotal.io/products/pcfdev#/releases/274428.

The error I see is ....
```log
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
Downloading Resources...
Progress: |====================>| 100.0%
Setting State...

Pivotal Telemetry
Are you ok with PCF Dev periodically capturing anonymized telemetry [y/N]?
> Y
Creating the VM...
Starting VPNKit...
Starting the VM...
Waiting for the VM...
Deploying the BOSH Director...
Deploying CF...
  Done (11m9s)
Deploying Apps-Manager...
  Done (2m22s)
Deploying Spring Cloud Services...
  Uploaded Releases: 51 (9m23s)FAILED
cf dev start: Failed to deploy services: Failed to deploy Spring Cloud Services: exit status 1
```
deploy-spring cloud services.log says
```log
Task 608 
15:06:53
Error: 'rmq/191fdcdb-6a82-42b1-a427-6a7ec8eaf8ba (0)' is not running after update. Review logs for failed jobs: rabbitmq-server
```
Not sure where the logs are "Review logs for failed jobs: rabbitmq-server"...
[deploy-spring cloud services.log](https://github.com/cloudfoundry-incubator/cfdev/files/2741500/deploy-spring.cloud.services.log)

**Comment by codeaches** [comment]
@aemengo , yes it is systematically failing for me (Tried few times). `cf dev stop` followed by `cf dev start -f pcfdev-pas.v.2.0.22.0-build.0.0.71-windows.tgz -s scs` results in exact same error.

fyi: `cf dev start -f pcfdev-pas.v.2.0.22.0-build.0.0.71-windows.tgz` works successfully, however I do need Spring Cloud Services hence I was trying with `-s scs` option.

**Comment by aemengo** [comment]
@codeaches Could please run the following commands and attach the artifact? Additionally you may be able to get more "real-time" assistance in the *cfdev* channel at https://cloudfoundry.slack.com.

```
$ cf dev bosh env | Invoke-Expression
$ bosh -d cf-rabbitmq-multitenant-broker logs
```

**Comment by arittner** [comment]
> 
> 
> @aemengo I am facing similar issue with "cf dev start -f pcfdev-pas.v.2.0.22.0-build.0.0.71-windows.tgz -s scs".
> I followed https://network.pivotal.io/products/pcfdev#/releases/274428.
> 
> The error I see is ....
> 
> ```
> Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
> Downloading Resources...
> Progress: |====================>| 100.0%
> Setting State...
> 
> Pivotal Telemetry
> Are you ok with PCF Dev periodically capturing anonymized telemetry [y/N]?
> > Y
> Creating the VM...
> Starting VPNKit...
> Starting the VM...
> Waiting for the VM...
> Deploying the BOSH Director...
> Deploying CF...
>   Done (11m9s)
> Deploying Apps-Manager...
>   Done (2m22s)
> Deploying Spring Cloud Services...
>   Uploaded Releases: 51 (9m23s)FAILED
> cf dev start: Failed to deploy services: Failed to deploy Spring Cloud Services: exit status 1
> ```
> 
> deploy-spring cloud services.log says
> 
> ```
> Task 608 
> 15:06:53
> Error: 'rmq/191fdcdb-6a82-42b1-a427-6a7ec8eaf8ba (0)' is not running after update. Review logs for failed jobs: rabbitmq-server
> ```
> 
> Not sure where the logs are "Review logs for failed jobs: rabbitmq-server"...
> [deploy-spring cloud services.log](https://github.com/cloudfoundry-incubator/cfdev/files/2741500/deploy-spring.cloud.services.log)

We facing exactly the same issue with pcf dev and the default memory settings (8GB). I've tried -m 10240 (fails on deploying scs) and currently -m 16834 (and still waiting).

With cf-dev the default memory 8GB is absolute the lowest limit. Sometimes it works, sometimes we get random failures. With -m 10240 it works much better. But if you have only 16GB physical RAM your system swaps around and slows down. Then you get randomly timeouts inside the VM (with different services) and the deployment fails at different stages. 

Currently it's very hard to setup a stable system and we tried it on different Windows 10 systems with 16GB and 32 GB physical RAM. Witch CF DEV and PCF-DEV (current alpha deployment from pivotal download side, January 8th).

**Comment by aemengo** [comment]
There's not much more to say on this. More than likely, `cf dev start` failing in this manner is due to a lack of system resources. We have our recommended system requirements listed here: https://github.com/cloudfoundry-incubator/cfdev#recommended-system-requirements. But please keep in mind that laptops typically have less power than their desktop counterparts.

As always, we will continue striving to improve user experiences with this product.

**Comment by airduster** [comment]
not a laptop, 4 cores, 16 gb ram
