### ISSUE TITLE
cf dev start: Unable to setup directories: failed to untar the desired parts of the tarball: gzip: invalid header

### ISSUE THREAD

**Issue by iamtpage** [cloudfoundry-incubator/cfdev#68]
Hi,

When I try to install pcf-dev with the latest cf dev (0.0.13), I get the following error:

```
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
Downloading Resources...

Progress: |>                    | 0%
Progress: |====================>| 100.0%
Setting State...
FAILED
cf dev start: Unable to setup directories: failed to untar the desired parts of the tarball: gzip: invalid header
```

The release before this one the deployment worked just fine. I also tried deleting the pcf-dev ISO file and redownloading it from pivnet, which results in the same error.

Operating System: Windows 10 with Hyper-V enabled
`cf dev` version: 0.0.13
`pcf-dev` version: `pcfdev-pas.v.2.0.22.0-build.0.101.0.iso`
Command run: `cf.exe dev start -f "pcf-dev.iso" -s redis`

**Comment by iamtpage** [comment]
Just confirmed installing cf dev `0.0.12` manually via `cf install-plugin -f` fixes this issue:

```
Creating the VM...
Starting VPNKit...
Starting the VM...
Waiting for Garden...
Deploying the BOSH Director...
Deploying CF...
 Uploaded Releases: 0 (1m30s)
```

**Comment by iamtpage** [comment]
Hi,

Thanks for the prompt reply. How soon is "shortly"? I have a deliverable that involves cf dev and pcf dev due by the end of the week and would like to use the new update if possible! Really looking forward to the reduction in start up time.

Thank you,

Tyler Page

-------- Original Message --------

**Comment by sdawson-pivotal** [comment]
Hey @iamtpage the pcf artifacts are up and ready for download:
https://network.pivotal.io/products/pcfdev

**Comment by iamtpage** [comment]
Holy cow, thanks for the quick turnaround! @sdawson-pivotal @aemengo

**Comment by sdawson-pivotal** [comment]
@iamtpage would you mind sharing a bit about your use case? We are looking to better understand how people are using CF / PCF Dev, and what they are looking for. Your answers to this 4 question survey would be very helpful to us: https://goo.gl/forms/3OHzU2S5907hiu5r1

**Comment by iamtpage** [comment]
@sdawson-pivotal Sure thing, just submitted my response.

**Comment by ranadeep-sh** [comment]
@iamtpage 
Did you try out the updated version mentioned by @sdawson-pivotal ?
I am still seeing the same error as you had observed earlier.

@sdawson-pivotal Please refer attached screen-shot and kindly let me know what I might have missed.
Thanks in advance.
![screenshot](https://user-images.githubusercontent.com/19390028/51951312-21f8d180-2402-11e9-8699-9b5c62645ce1.JPG)

**Comment by iamtpage** [comment]
@ranadeep-sh yes, upgrading both cf dev and pcf-dev to their latest versions resolved the issue for me

**Comment by basilk27** [comment]
I am getting this error on Releases: v1.2.0 for PAS 2.4.4
Basils-MBP:~ basilkiwanuka$ cf dev start -f /Users/basilkiwanuka/Utils/Pivotal_Tools/pcfdev-v1.2.0-darwin.tgz
Downloading Network Helper...
Progress: |====================>| 100.0%
Installing cfdevd network helper (requires administrator privileges)...
Password:
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
Downloading Resources...
Progress: |====================>| 100.0%
Setting State...
FAILED
cf dev start: Unable to setup directories: unexpected EOF
