### ISSUE TITLE
Normal user missing windows cfdev

### ISSUE THREAD

**Issue by jsfranko** [cloudfoundry-incubator/cfdev#69]
Normal “user” missing in windows 0.0.13 cf dev start -f ..., only admin user exists with system org and space.

**Comment by aemengo** [comment]
@jsfranko Unfortunately, we're not able to reproduce. The password for the normal "user" is `pass`. If the following does not work for you, you might have had a bad start session:

```
 cf login -a api.dev.cfdev.sh --skip-ssl-validation -u user -p pass

**Comment by jsfranko** [comment]
I think we used the right cf commands to look for the accout and it appeared not
To exist. After dev stop and another dev start, the user account worked. If we see it happen again what logs can we gather for you?

**Comment by aemengo** [comment]
@jsfranko The logs to look out for in this case can be found here: `~\.cfdev\log\deploy-cf.log`. If this issue happens again, then it would be evident in that file, towards the bottom. Moreover, most of the logs that pertain to CF Dev can be found in `~\.cfdev\log`.

If this is functionality that is not working robustly, then we'll be sure to address it.
