### ISSUE TITLE
Progress bar for "Downloading Resources..."?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/cfdev#7]
I'm personally aware how big BOSH + CF is, so as I watch `Downloading Resources...` Like a child on a long family car trip, I am definitely wondering "Are we there yet?"

Can we add a progress bar/estimate of time? Perhaps a new person thinks this `Downloading Resources...` is a quick thing and doesn't realise that on their slow Internet it might be hours?

**Comment by sclevine** [comment]
Definitely, we just didn't get a chance to port the download bar from the PCF Dev plugin before releasing the alpha.

**Comment by ssisil** [comment]
Added in [Release v0.0.3](https://github.com/cloudfoundry-incubator/cfdev/releases/tag/v0.0.3)
