### ISSUE TITLE
cf service-key host name (now ip address) not accessable from outside

### ISSUE THREAD

**Issue by s-h-o-g-u-n** [cloudfoundry-incubator/cfdev#73]
Version pcfdev-v0.30.0 and older versions generates a host name like redis-broker.local.pcfdev.io for a redis service. 
```
cf service-key my_redis EXTERNAL-ACCESS-KEY:
{
  "host": "redis-broker.local.pcfdev.io",
  "password": "s/a00BeOQnv3f9ZDfX51TbF......=",
  "port": 6379
}
```
With pcfdev-pas.v.2.0.22.0-build.0.0.71-windows and the latest cf cli version 6.42, the service-key command shows now an IP address.
```
{
  "host": "10.144.0.23",
  "password": "s/a00BeOQnv3f9ZDfX51TbF......=",
  "port": 6379
}
```
This IP Address is not accessable from outside cf, like the redis-broker.local.pcfdev.io address before.

Use case: Access the redis service from outside cloud foundry, an IDE for example.

**Comment by aemengo** [comment]
@s-h-o-g-u-n Apologies for the delay on this. CF Dev (and CF itself) has gone through many changes and I wanted to make sure that you were getting the appropriate response. The best way going forward to interact with your redis instance is via CF ssh _port forwarding_. In this case, if you've bound "my-app" to this redis instance, if would look like this:

```
cf ssh -L 6379:10.144.0.23:6379 my-app
```

Then you could access the redis service with the host as `127.0.0.1` from the outside. You can read more about CF ssh port fowarding here: https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-services.html

**Comment by s-h-o-g-u-n** [comment]
Hi @aemengo, thanks for ur response. The problem with ur suggested solution is, there is no app in my use case scenario. I want to access the service without any pushed app from outside cf. It was possible in the "old" 0.30 Version. From my point of view as an app developper, I want to run a micro service with full access to the rabbitmq and redis service, before I push it to cf.

**Comment by aemengo** [comment]
@s-h-o-g-u-n You're making valid points but, unfortunately, there's not much that this team can do to alleviate this issue. We are only responsible for packaging CF for a local use case, but the functionality that you're referring simply is no longer present in the newer releases of the [redis release](https://github.com/pivotal-cf/cf-redis-release/).
