### ISSUE TITLE
cf dev start: Unable to setup directories: failed to untar the desired parts of the tarball: gzip: invalid header

### ISSUE THREAD

**Issue by ranadeep-sh** [cloudfoundry-incubator/cfdev#74]
Can someone help in finding out what I am missing that's causing startup failure (seen in 1st screenshot)?

As you can see in 2nd screenshot, I am using the latest version of the CF CLI tool.
![cf_dev_start_error](https://user-images.githubusercontent.com/19390028/51951499-dbf03d80-2402-11e9-97e4-208c724fe1d5.JPG)
![screenshot](https://user-images.githubusercontent.com/19390028/51951502-df83c480-2402-11e9-8276-ba995da647b9.JPG)

**Comment by aemengo** [comment]
Passing that iso to the `-f` flag is the incorrect way to invoke the tool. You instead need to pass the tarball that you recently downloaded off of Pivotal Network to the `-f` flag. For example:

```
cf dev start -f ~\Downloads\pcfdev-pas.v.2.0.22.0-build.0.0.71-windows.tgz

**Comment by ranadeep-sh** [comment]
Thanks @aemengo for the quick response.
It looks like the startup required atleast 8GB of RAM (attached screenshot).
Is there a way to start by specifying less than 8 GB of RAM ?
![need_4_8gb_ram_error](https://user-images.githubusercontent.com/19390028/52099246-61f5bb00-25a0-11e9-94dc-50d4394ade9b.JPG)

**Comment by aemengo** [comment]
@ranadeep-sh That's just a warning message, I don't think memory was the reason that start failed here. Perhaps the VM was put in a bad state from the previous run. Please execute a stop command (to clean up any leftover state) and then start again.

```
cf dev stop
cf dev start -f C:\Users...
```

In addition, you can specify memory to the start command with the `-m` flag in megabytes, but I'd only recommend using the flag to _increase_ the memory allocation, not lower it.

**Comment by aemengo** [comment]
@ranadeep-sh Unfortunately, I think you've uncovered a bug. Our code is not ready for the literal space character `' '` in your HOME directory path. The workaround would be to change the working directory of CF Dev to a location without a space character, via the `CFDEV_HOME` environment variable. For example:

```
cf dev stop
$env:CFDEV_HOME="C:\cfdev"
cf dev start -f .\pcfdev-pas....
```

Please let us know if this works for you and we'll rectify the issue as soon as we can.

**Comment by ranadeep-sh** [comment]
@aemengo 
Thank you. I will definitely try this out and get back.
Appreciate your prompt response.

**Comment by ranadeep-sh** [comment]
I changed the path, as suggested.
But still running into same issue.
![cf_dev_start_error](https://user-images.githubusercontent.com/19390028/52318757-0f4b4300-2994-11e9-99c6-dac565edaf33.JPG)

**Comment by aemengo** [comment]
@ranadeep-sh That looks like a new powershell window. If you set the environment in _another_ powershell window, it will not carry over into a new one. You can see if it applied by executing `dir env:` in your current window and seeing if `CFDEV_HOME` is the table printed.

Please try the command again but this time in the same window that you are executing `cf dev start` in. You will know that it has been successfully applied because the directory (`"C:\cfdev"` in my example) will have been created for you.

**Comment by ranadeep-sh** [comment]
@aemengo 
Hi Anthony. I tried setting said environment variable and then running the start command. It complains that the tar file could not be found. So, I re-ran start command with full path of tar file and this time it created the following files.
![cf_dev_start_error](https://user-images.githubusercontent.com/19390028/52384326-0ff2e080-2a4b-11e9-9d12-41cf3a747fba.JPG)

But, unfortunately, the CLI powershell closed by itself. 
Now, when I try to run the start command again (without or, without the tar file), there's no message on the current status and attempting to connect to my local instance is failing. I have a feeling that the instance is not running.
![cf_dev_start_error](https://user-images.githubusercontent.com/19390028/52384456-94ddfa00-2a4b-11e9-8439-976c50e7499f.JPG)

**Comment by ranadeep-sh** [comment]
@aemengo 
A ping to the hostname went fine, though. Strange.
![cf_dev_start_error](https://user-images.githubusercontent.com/19390028/52384982-cd7ed300-2a4d-11e9-828d-ffa287980c30.JPG)

**Comment by aemengo** [comment]
@ranadeep-sh `cf dev ...` commands giving no output is definitely cause for concern. There must be some invalid state for this to be happening. Perhaps it is worth killing any **cf** processes in Activity Monitor before trying again. If the powershell windows exited, then there's a chance that the start command was running in the background.

For more real-time assistance, please try the `#cfdev` channel at https://cloudfoundry.slack.com

**Comment by ranadeep-sh** [comment]
Hi @aemengo ,

I am disappointed that you closed the issue even without coming to a reasonable conclusion. 

1) It doesn't make sense to even attempt running PCFDEV with memory limitation < 8 GB when it itself is saying 8 GB is needed at a minimum. Now, I have upgraded my laptop's physical memory to 16 GB. But, restart is still failing at Step# 8 of 14, everytime. **Is there some log file generated locally that captures the errors ?**

2) I am looking for expert guidance in this forum, rather than looking elsewhere.

**Comment by aemengo** [comment]
@ranadeep-sh Sorry I'm a bit overzealous about closing these because it gets really hard to manage new items when these pile up. Moreover, I hadn't heard any response from you in a while from either here or our public slack forum (where we can assist you in a more real-time manner).

But the answer to `1.` is **yes**. The log files can be found at `~/.cfdev/log` (provided that the CFDEV_HOME environment variable hasn't been used). In this case, the specific file that might be useful is at `~/.cfdev/log/deploy-cf.log`
