### ISSUE TITLE
dev.cfdev.sh connect to host (Mac)

### ISSUE THREAD

**Issue by bitsnbites010** [cloudfoundry-incubator/cfdev#75]
host running mongo db at localhost:27017
cfdev running node app

using local IP address or host.cfdev.sh errors out with message "MongoNetworkError: connect ECONNREFUSED"

**Comment by aemengo** [comment]
@bitsnbites010 If your mongodb instance is only accessible by _localhost_, this could be an issue because your node app will have its own notion of localhost while running in CF. Could you try having mongodb listen on all interfaces `@0.0.0.0:27017` and see if the issue persists?

**Comment by bitsnbites010** [comment]
my mongo instance running on local is open to accept connections from any connector on the network. what I am looking for is something similar to https://github.com/pivotal-cf/pcfdev/blob/master/FAQ.md but for cf dev.

**Comment by aemengo** [comment]
@bitsnbites010 Connections from CF Dev applications to the host machine is something we explicitly test before release so I'd be very surprised if this was not working out the box. But here are some troubleshooting instructions to help isolate the issue.

First we check to see that the dns name `host.cfdev.sh` is getting resolved correctly. It should look like below:
```bash
$ cf ssh <my-node-app> -c 'host host.cfdev.sh'
host.cfdev.sh has address 192.168.65.2
```

Then I'm checking that connections can be made from the app container to a very simple server.
```bash
# In one terminal window
$ ruby -run -e httpd . -p 8000
...
$ cf ssh <my-node-app> -c 'nc -v host.cfdev.sh 8000'
Connection to host.cfdev.sh 8000 port [tcp/*] succeeded!
^C
```

Finally we check connections to the mongodb server in question.
```bash
$ cf ssh <my-node-app> -c 'nc -v host.cfdev.sh 27017'
nc: connect to host.cfdev.sh port 27017 (tcp) failed: Connection refused
^C
```

If it fails at the final check, like above, then we have to conclude that there's something off about your mongodb server: the port is wrong, etc. If it passes all three, then there might be an issue with how your application is configured to consume the database url.

**Comment by bitsnbites010** [comment]
switched my host connection to use host.cfdev.sh and it works... thanks much @aemengo 

is this documented somewhere?

**Comment by aemengo** [comment]
@bitsnbites010 At this moment, the new documentation is not up yet. I apologize for the misleading information that lead you astray the first time.
