### ISSUE TITLE
Windows 10 Hyper V host.cfdev.sh mapping lost after network switch

### ISSUE THREAD

**Issue by guptaavi** [cloudfoundry-incubator/cfdev#76]
After initially starting cfdev on my Windows 10 laptop, applications running on cfdev are able to access the host using host.cfdev.sh. But after "pausing" the VM in Hyper-V, suspending laptop and then "resuming" the VM, the deployed applications are no longer able to access services (e.g. mongodb) running on the host using host.cfdev.sh (Exception: java.net.UnknownHostException: host.cfdev.sh). 
I would like to avoid having to stop and start the dev instance daily since it takes upwards of 30 minutes to start. 
If there any particular sequence of shutdown steps I need to follow in order to avoid having to stop/start the VM each time?

**Comment by sdawson-pivotal** [comment]
Hi @guptaavi thank you for reaching out. Would you mind telling us more about your cf dev use case? We are gathering feedback from our users and your input would be much appreciated. Here is a 4 question survey: https://goo.gl/forms/pztZuTcEgoK4jSjz1 Thank you!

**Comment by guptaavi** [comment]
Anyone who can help with this issue? I noticed that after doing 'cf dev start' I can use the jumpbox account to ssh into the Hyper-V VM. From this ssh session, I am able to do a nslookup host.cfdev.sh. However, after a network switch, this host mapping is lost. Any ideas on how to "manually" restore the routes on the VM and on the host?

**Comment by aemengo** [comment]
@guptaavi Unfortunately, this is functionality that we simply do not support as of right now, primarily because Hyper-V is the component orphaning the virtual network switch, not us. As of right now, we have no resolution to advise.
