### ISSUE TITLE
CF DEV start failed for 0.0.13 build

### ISSUE THREAD

**Issue by emailtowalter** [cloudfoundry-incubator/cfdev#77]
Upgrade to 0.0.13 CLI on my macbook. 

Run cf dev stop, then cf dev start....
"
Downloading Network Helper...
Progress: |====================>| 100.0%
Installing cfdevd network helper...
Installing networking components (requires root privileges)
Password:
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
Downloading Resources...
Progress: |====================>| 100.0%
Setting State...
Creating the VM...
Starting VPNKit...
Starting the VM...
Waiting for the VM...
Deploying the BOSH Director...
Deploying CF...
  Uploaded Releases: 32 (1m17s)FAILED
cf dev start: Failed to deploy the Cloud Foundry: Failed to deploy cf: exit status 1
"
My version info: 
cf dev version
CLI: 0.0.13

cf: v6.8.0
cf-mysql: 36.16.0

Run the command with and without HTTPS_PROXY. same result. It was working for build 0.0.12.

**Comment by aemengo** [comment]
@emailtowalter could you please post the contents of `~/.cfdev/log/deploy-cf.log`?

**Comment by emailtowalter** [comment]
here you go. it seems the I cannot download https://storage.googleapis.com/cf-deployment-compiled-releases/bosh-dns-aliases-0.0.3-ubuntu-xenial-170.13-20181214-220259-630417653.tgz. I tried to use CURL, it worked. 

In browser, I can see the site's root cert, intermedia cert are replaced with our own company's certs and SSL revocation cert for security reason. 

"Using environment '10.144.0.4' as client 'admin'

Using deployment 'cf'

Release 'cf-networking/2.20.0' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'cf-mysql/36.16.0' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'binary-buildpack/1.0.27' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'bpm/1.0.0' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'capi/1.74.0' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'cf-syslog-drain/8.1' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'cflinuxfs3/0.46.0' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'credhub/2.1.2' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'cflinuxfs2/1.255.0' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'diego/2.25.0' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'dotnet-core-buildpack/2.2.0' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'go-buildpack/1.8.29' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'java-buildpack/4.16.1' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'garden-runc/1.17.1' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'nodejs-buildpack/1.6.34' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'loggregator/104.4' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'nats/26' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'php-buildpack/4.3.64' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'routing/0.184.0' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'ruby-buildpack/1.7.27' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'python-buildpack/1.6.23' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'silk/2.20.0' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'staticfile-buildpack/1.4.35' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'statsd-injector/1.5.0' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'uaa/66.0' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'loggregator-agent/3.2' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'log-cache/2.0.2' for stemcell 'ubuntu-xenial/170.13' already exists.

Release 'cf-cli/1.11.0' for stemcell 'ubuntu-xenial/170.13' already exists.

Task 42

Task 42 | 15:59:05 | Downloading remote release: Downloading remote release (00:00:00)
                   L Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
Task 42 | 15:59:05 | Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

Task 42 Started  Thu Feb 14 15:59:05 UTC 2019
Task 42 Finished Thu Feb 14 15:59:05 UTC 2019
Task 42 Duration 00:00:00
Task 42 error

Creating and uploading releases:
  - Uploading release 'bosh-dns-aliases/0.0.3':
      Uploading remote release 'https://storage.googleapis.com/cf-deployment-compiled-releases/bosh-dns-aliases-0.0.3-ubuntu-xenial-170.13-20181214-220259-630417653.tgz':
        Expected task '42' to succeed but state is 'error'

Exit code 1
"

**Comment by aemengo** [comment]
@emailtowalter the implementation details from `0.0.12` -> `0.0.13` are significant. I believe that is the only artifact retrieved from the internet for the start process. Is there a way that you can make the certificate at that domain trusted for your machine and then try again?

**Comment by emailtowalter** [comment]
The problem is that I believe it is trusted already. The evidence is that curl command works. 

Other than the standard keystone on my MacBook, anywhere else I should add certain into?

Walter Wu

**Comment by aemengo** [comment]
@emailtowalter Thank you for submitting an issue about this. This is definitely a bug on our end: nothing should be downloaded from the internet during the start process. With your assistance, we've just resolved this issue and the next release will not have this behavior.

Regardless, for now, the problem you're having is evident. That url cannot be downloaded on your machine and it is very likely something specific to your environment, perhaps because of the revocation certificate. See if a system administrator can help you. The file size is only `4.0K`.

**Comment by emailtowalter** [comment]
Good to know that it helps. What is the eta for the next release?

Walter Wu

**Comment by kishorekkota** [comment]
I am running into same issue. Can someone help with instruction on how to make this file available to cfdev ? Or any ETA on next release ?

**Comment by aemengo** [comment]
@emailtowalter @kishorekkota Apologies for the delay. The next release is finally available, with the discussed issue resolved.

```
$ cf install-plugin -r CF-Community cfdev -f
$ cf dev version
CLI: 0.0.14
BUILD: 33 (026b7aa)
...
```
