### ISSUE TITLE
No tiene ningún binario disponible para la plataforma.

### ISSUE THREAD

**Issue by Oxicode** [cloudfoundry-incubator/cfdev#79]
![image](https://user-images.githubusercontent.com/1320709/53598569-1ae4f080-3b73-11e9-929d-e0279a39c296.png)

**Comment by aemengo** [comment]
There's currently no offering of this product on the linux platform. Your only option is to retrieve our previous deprecated product here:

https://network.pivotal.io/products/pcfdev#/releases/314093
