### ISSUE TITLE
sudo: illegal option -- -

### ISSUE THREAD

**Issue by jallwrig** [cloudfoundry-incubator/cfdev#8]
Trying to install on MacOs; I previously had an install of pcfdev on the same machine.

johns-MacBook-Pro-183:~ johnallwright$ cf install-plugin downloads/cfdev-v0.0.1-darwin
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin downloads/cfdev-v0.0.1-darwin? [yN]: y
Installing plugin cfdev...
OK
Plugin cfdev 0.0.1 successfully installed.
johns-MacBook-Pro-183:~ johnallwright$ cf dev start
Setting up IP aliases for the BOSH Director & CF Router (requires root privileges)
sudo: illegal option -- -
usage: sudo -h | -K | -k | -L | -V
usage: sudo -v [-AknS] [-g groupname|#gid] [-p prompt] [-u user name|#uid]
usage: sudo -l[l] [-AknS] [-g groupname|#gid] [-p prompt] [-U user name] [-u user name|#uid] [-g groupname|#gid] [command]
usage: sudo [-AbEHknPS] [-C fd] [-g groupname|#gid] [-p prompt] [-u user name|#uid] [-g groupname|#gid] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-C fd] [-g groupname|#gid] [-p prompt] [-u user name|#uid] file ...
Error encountered running 'start' : Unable to alias BOSH Director/CF Router IP: exit status 1

**Comment by ekcasey** [comment]
Hi @jallwrig, would you mind running `sudo --version` and telling us which version of sudo is on your path?

**Comment by jallwrig** [comment]
Hi, sudo -V returns:

Sudo version 1.7.10p9

thanks!

**Comment by ekcasey** [comment]
`cfdev` is using sudo syntax that will only work with sudo version 1.8.0 and above. This will limit the versions of osx that cfdev is currently compatible with. 

We will likely be removing this limitation soon. Which version of osx are you running?

**Comment by jallwrig** [comment]
I'm on 10.11.6 El Capitan, I guess I should upgrade to High Sierra.

**Comment by jallwrig** [comment]
upgrading Macos to High Sierra fixed the issue - thanks!

**Comment by ssisil** [comment]
Fixed in [Release v0.0.3](https://github.com/cloudfoundry-incubator/cfdev/releases/tag/v0.0.3)
