### ISSUE TITLE
Unable to start cfdev 1.1.0 on Windows

### ISSUE THREAD

**Issue by soickm** [cloudfoundry-incubator/cfdev#81]
Good evening,

I am trying to install cf dev on a windows pro with 16GB of RAM.

After a lengthy download and following the instructions provided on https://docs.pivotal.io/pcf-dev/install-windows.html,

It has been over 30 minutes and all I see is:
```
D:\projects\CloudFoundry>cf dev start -f pcfdev-v1.1.0-windows.tgz
Setting up IP aliases for the BOSH Director & CF Router (requires administrator privileges)
Downloading Resources...
Progress: |====================>| 100.0%
Setting State...
```
There isn't a log telling me what happened, nor any indication of what is happening.

I don't see any troubleshooting guides for pcfdev, so I don't know exactly what to do next.

Thanks,

Pedro

**Comment by soickm** [comment]
If it helps:

C:\Users\root>cf dev version

CF Dev collects anonymous usage data to help us improve your user experience. We intend to share these anonymous usage analytics with user community by publishing quarterly reports at :

https://github.com/pivotal-cf/cfdev/wiki/Telemetry

Are you ok with CF Dev periodically capturing anonymized telemetry [y/N]?> N
CLI: 0.0.14
BUILD: 33 (026b7aa)

pas: 2.4.3
p.mysql: 2.5.3-build.7
p.redis: 2.0.1
p.rabbitmq: 1.15.4
p.spring-cloud-services: 2.0.6

**Comment by soickm** [comment]
Ok - so after a good 20 minutes I got this:

Setting State...
Creating the VM...
Starting VPNKit...
Starting the VM...
FAILED
cf dev start: starting the vm: start-vm: failed to execute: powershell.exe -Command "Start-VM -Name cfdev": exit status 1: Start-VM : 'cfdev' failed to start.
Synthetic SCSI Controller (Instance ID 21EFE75D-9669-4F99-917C-5288B27FAFE7): Failed to Power on with Error 'The
requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be
uncompressed and unencrypted and must not be sparse.'.
Attachment 'C:\Users\root\.cfdev\state\disk.vhdx' failed to open because of error: 'The requested operation could not
be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted
and must not be sparse.'.
'cfdev' failed to start. (Virtual machine ID 10A04ADA-012A-44AE-93AD-67547633295F)
'cfdev' Synthetic SCSI Controller (Instance ID 21EFE75D-9669-4F99-917C-5288B27FAFE7): Failed to Power on with Error
'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must
be uncompressed and unencrypted and must not be sparse.' (0xC03A001A). (Virtual machine ID
10A04ADA-012A-44AE-93AD-67547633295F)
'cfdev': Attachment 'C:\Users\root\.cfdev\state\disk.vhdx' failed to open because of error: 'The requested operation
could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and
unencrypted and must not be sparse.' (0xC03A001A). (Virtual machine ID 10A04ADA-012A-44AE-93AD-67547633295F)
At line:1 char:1
+ Start-VM -Name cfdev
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.StartVM

Could this be disk space related? What size of VHD are you trying to create?

**Comment by soickm** [comment]
OK - so I think it has to do with either disk space or the fact the boot disk is compressed. But I configured hyper-V to create vhd on another drive. It isn't good practice to create VHD on the boot disk anyway. Is there some hard coding to write V disks on the root volume and the root user?

**Comment by aemengo** [comment]
> What size of VHD are you trying to create?

The VHD is currently `~18GB` in size, before provisioning. If you're saying that `C:` Drive is compressed, then that's probably the issue.

> Is there some hard coding to write V disks on the root volume and the root user?

By default, it uses the current user and the current user's home directory. You can configure a different working directory by using the `$CFDEV_HOME` environment variable:

```
> $env:CFDEV_HOME="D:\cfdev"
> cf dev start -f ...
```
