### ISSUE TITLE
Unable to start pcfdev on Windows 10 due to folder creation error

### ISSUE THREAD

**Issue by zoosm3** [cloudfoundry-incubator/cfdev#82]
Hello,

I am using Windows 10 and tried `cf dev start` but failed. I run the following command with an  Administrator user. 

```
PS C:\WINDOWS\system32> cf dev start -f C:\Users\myuser\Downloads\pcfdev-v1.1.0-windows.tgz
FAILED
cf dev start: checking whether hyperv is enabled: failed to execute: powershell.exe -Command "(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V -Online).State": exit status 1: Get-WindowsOptionalFeature : An error occurred. The directory in the temporary folder C:\Users\myuser\AppData\Local\Temp\ could not be created.
Ensure that the path to the temporary folder exists and that you have Read/Write permissions on the folder.
At line:1 char:2
+ (Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V -Online).S ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsOptionalFeatureCommand
```

It says "The directory in the temporary folder C:\Users\myuser\AppData\Local\Temp\ could not be created.", but I can create a file in `C:\Users\myuser\AppData\Local\Temp\` using `copy` command and my user has a full privileged access permission to the folder .

Is there any permission setting on my Windows?

Any help would be appreciated,
Thanks.

**Comment by aemengo** [comment]
@zoosm3 Unfortunately, we're ill-equipped to help here, as this issue seems to stem from your machine and not CF Dev itself.

You can perhaps reach out to the Microsoft forums why the following command does not work on your machine:
```
Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V -Online
```
