### ISSUE TITLE
How to enable Windows 10 Hyper-V support ?

### ISSUE THREAD

**Issue by loganmzz** [cloudfoundry-incubator/cfdev#83]
When I run `cf dev start`, I got: `FAILED Error: could not find VBoxManage executable.`

How to get it working with Windows 10 Hyper-V ?

**Comment by aemengo** [comment]
@loganmzz You're not using the current iteration of CF Dev (the one produced by this repository). Please perform the following to upgrade:

```
> cf uninstall-plugin pcfdev
> cf install-plugin -r CF-Community cfdev
> cf dev version
CLI: 0.0.15
BUILD: 54 (35368e4)
```
And then you can perform a start with Hyper-V support.
