### ISSUE TITLE
bosh.yml

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry-incubator/cfdev#85]
Can you tell me how to obtain the bosh manifest file for cfdev - Thanks

**Comment by aemengo** [comment]
If you'd like to see the manifest for the director _simply for reference_, you can find it at: `~/.cfdev/state/bosh/director.yml`

However, please note that cannot directly deploy that file as is. CF Dev does a few other related provisioning steps before creating the director. Making modifications is not supported as of right now.

**Comment by betht1220** [comment]
Great, thank you for the reply. I appreciate it @aemengo
