### ISSUE TITLE
uaa

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry-incubator/cfdev#86]
I notice that pcfdev v1.2.0 does not have a uaa vm? or am I missing something.
I need to connect this uaa vm to ldap server

Thanks

**Comment by aemengo** [comment]
No, you're not missing something

A major change in `v1.2.0` was that it was built to model [Small Footprint PAS](https://docs.pivotal.io/pivotalcf/2-4/customizing/small-footprint.html). Thus, there isn't an explicitly titled VM with uaa all by itself. Instead, you can find UAA colocated on the `control` VM.

**Comment by betht1220** [comment]
@aemengo I intend to deploy some bosh-release, will this be okay then? I note that the foundation take around 8GIG of memory, hope that PAS small footprint will leave more memory for me to deploy more bosh releases for use? Thank you for your inputs

**Comment by aemengo** [comment]
The following was just taken on the VM with a couple services running: It seemed to have consumed `6.8GB` of RAM.
<img width="1243" alt="Screen Shot 2019-04-20 at 12 07 52 PM" src="https://user-images.githubusercontent.com/4236888/56459781-b40bd880-6366-11e9-99b4-dd05ea521aea.png">

I'd say it should be fine to deploy something else, but it also does depend on your bosh-release.
In any event, I want to remind you that you can use the **-m** flag to `cf dev start` to specify how much memory you want allocated to the VM _in MB_.

**Comment by betht1220** [comment]
Thank you @aemengo - you can close this issue
