### ISSUE TITLE
bosh login failed

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry-incubator/cfdev#87]
I tried to "bosh login" using credential "ops_manager" and its $BOSH_CLIENT_SECRET, but got 
Failed to authenticate with UAA

Where can I find credentials to "bosh login" - Thanks

**Comment by aemengo** [comment]
Running “cf dev bosh env” should output the environment variables. “cf dev bosh” should give you instructions on how to load these variables into your shell.

Does that work for you?

**Comment by betht1220** [comment]
yes, it works. Thank you @aemengo

**Comment by betht1220** [comment]
Don't know why I have to issue the load command every so often to bosh login.  I should only need to load it once, correct?
Also, can you tell me the URL to credhub associated with the pcfdev cloud foundry deployment? or this is not the right forum for pcfdev.?

**Comment by aemengo** [comment]
> Don't know why I have to issue the load command every so often to bosh login. I should only need to load it once, correct?

Yes, you should only have to load it once, _once per shell session_. If you are entering new console windows, you'll have to perform the load command again.

> Also, can you tell me the URL to credhub associated with the pcfdev cloud foundry deployment?

The BOSH _director credhub_ can be found at `10.144.0.2:8844`. The internal credhub that utilized for PAS deployment is not accessible from outside of the VM  

> is this the right forum for pcfdev.?

Yes, it is :)
