### ISSUE TITLE
pcfdev diskspace usage

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry-incubator/cfdev#90]
My system ran out of diskspace while running pcfdev.
1. where does pcfdev put its data on my local disk?
2. Can I configure to have pcfdev put data on an external disk instead?
I noticed that it uses 50G - 60G of diskspace.

Thanks

**Comment by aemengo** [comment]
Yes you can configure where CF Dev puts its data. The explanation to this can be found in our FAQ below:

https://github.com/cloudfoundry-incubator/cfdev/blob/master/FAQ.md#can-i-configure-the-working-directory
