### ISSUE TITLE
Migrate MySQL service to pxc-release?

### ISSUE THREAD

**Issue by menicosia** [cloudfoundry-incubator/cfdev#92]
Hi there! I saw in issue #35 that cf-dev has added a MySQL service.

That’s great! But I think that it’s using the cf-mysql release and broker. We aren’t actively maintaining that, as we have moved on to pxc-release some time ago. That distribution doesn’t have a broker, rather uses the (Pivotal) OSS project, on-demand-broker.

What are CF Devs’ requirements around a broker, does it need to be synchronous, is there a BOSH to communicate with, etc etc? How can we better help support CF Dev?

Love,
CF MySQL PMs

**Comment by aemengo** [comment]
@menicosia Thank you very much for poking us about this. We've looked into the [pxc-release](https://github.com/cloudfoundry-incubator/pxc-release) months earlier but promptly ended our investigation when we couldn't figure about how to make the service available in the CF marketplace. We're already using pxc as CF's internal datastore so being able to streamline our deployments by using the same distribution as a CF service is very appealing to us.

As for CF Dev, it doesn't need a special requirements around a broker: synchronous or asynchronous will work fine. CF Dev is effectively a BOSH Lite with CF pre-packaged. It has a BOSH director to communicate and perform deployments with.

The reason for our preference for the deprecated cf-mysql-release is the existence of the [cf-mysql-deployment](https://github.com/cloudfoundry/cf-mysql-deployment) repository. The repo makes it very easy for our CI pipelines to consume new updates. Is there anything that serves a similar purpose for pxc coupled with the OSS on-demand-broker?

**Comment by menicosia** [comment]
Hm. There isn’t. Thanks for the info about cfdev is like a bosh-lite, that helps us think about it. I’ll try to find some time to follow up in the next few weeks.
