### ISSUE TITLE
cf login --sso does not show passcode prompt

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/cfdev#93]
See https://github.com/cloudfoundry/cli/pull/1624

Are you aware of whether you are explicitly not passing a `passcode` prompt or if there is a fix for CF Dev?

I think this issue is broader than CF Dev only, but @abbyachau is not able to reproduce it; and I don't have any OSS CF deployments running aside from CF Dev to reproduce it either. I cannot see any mention of `passcode` in cf-deployment; and only see it mentioned in uaa-release for OIDC example https://github.com/cloudfoundry/uaa-release/blob/b91170724896928d87cc0066e6c2e158cca6c53d/jobs/uaa/spec#L938-L975

**Comment by aemengo** [comment]
@drnic We're not explicitly omitting a `passcode` prompt. Internally, CF Dev is using cf-deployment.

Since PR is focused on the CF CLI, would you be satisfied with this issue being resolved?
