### ISSUE TITLE
Feature offer: cf dev deploy-service docker-redis, docker-postgresql, etc

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/cfdev#94]
Currently `cf dev deploy-service` offers mysql.

If you'd like I could investigate adding support for a range of dev/test services based on https://github.com/cloudfoundry-community/docker-broker-deployment

I would upgrade the docker images etc as part of the work (I've not worked on this project for couple years).

This would allow cf dev users to install redis, postgresql, kafka, etc as single-node dedicated services via BOSH/Docker

**Comment by aemengo** [comment]
We appreciate the feature offer, but there's no need to invest the time into it.

CF Dev is quite "full" already and additional services are only _considered_ if there is overwhelming demand for it. Moreover, we're trying to mimic a production environment as closely as we can. If you were initially looking for more services than `mysql`, you can following the instructions in the [FAQ](https://github.com/cloudfoundry-incubator/cfdev/blob/master/FAQ.md#the-only-service-available-is-mysql-how-do-i-get-access-to-pivotal-apps-manager-rabbitmq-redis-spring-cloud-services) to do so. Finally, if you were looking for a way to access services on the host from within an application container, CF Dev allows you do so with the `host.cfdev.sh` hostname.
