### ISSUE TITLE
Where is CI pipeline described?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/cfdev#95]
I've looked in:
* https://github.com/cloudfoundry-incubator/cfdev
* https://github.com/cloudfoundry-incubator/cfdev-builder

I don't think I spot a [concourse] CI pipeline. Where are the pipeline + build scripts? Thanks!

**Comment by aemengo** [comment]
Our CI pipeline + build scripts are not publicly available.

**Comment by drnic** [comment]
@aemengo can I ask why the pipeline/scripts description is not publicly visible?
