### ISSUE TITLE
How to access "dev.cfdev.sh" from another computer running in same network

### ISSUE THREAD

**Issue by betht1220** [cloudfoundry-incubator/cfdev#98]
Due to lack of memory space, I have to run a pipeline on a different machine.  This pipeline needs to access "api.dev.cfdev.sh" running in my local laptop.  
How do I set up to allow the pipeline to access the API endpoint?
Thanks

**Comment by aemengo** [comment]
I'm sorry Beth, but this is one use case that we do not support. CF Dev is recommended for local use only and was not built with remote access in mind. We would much rather you consider other options: like a cloud deployment of [cf-deployment](https://github.com/cloudfoundry/cf-deployment).

**Comment by betht1220** [comment]
thank you @aemengo
