### ISSUE TITLE
`cf install-plugin cfdev` never finishes

### ISSUE THREAD

**Issue by paulvi** [cloudfoundry-incubator/cfdev#99]
Hello

`cf install-plugin cfdev` never finishes,  
and there is no any errors or warning why it cann't or what it is doing.

P.S. Environment Windows 10, Gish Bash and cmd.

![image](https://user-images.githubusercontent.com/1614482/57498470-92bb5e00-730e-11e9-9e44-fbb6f32da63a.png)

**Comment by paulvi** [comment]
the same with Windows `cmd`

![image](https://user-images.githubusercontent.com/1614482/57509692-7c75c800-7337-11e9-907d-f6dc26f343f5.png)

**Comment by aemengo** [comment]
@paulvi It looks like `cflocal` hangs on install for you too: this can't be a CF Dev specific issue. I'm afraid that we're ill-equipped to help you with this issue since our code hasn't even had the chance to run yet. Perhaps the [cf cli](https://github.com/cloudfoundry/cli) team can help you.

**Comment by paulvi** [comment]
Raised as https://github.com/cloudfoundry/cli/issues/1647
